package gutta.apievolution.jmh.inprocess.provider;

public class ProviderApiV1 {
    
    private static final ProviderResult10 RESULT_10 = createProviderResult10();
    
    private static ProviderResult10 createProviderResult10() {
        ProviderResult10 result = new ProviderResult10();
        
        result.setIntField1(1234);
        result.setIntField2(1234);
        result.setIntField3(1234);
        result.setIntField4(1234);
        result.setIntField5(1234);
        result.setIntField6(1234);
        result.setIntField7(1234);
        result.setIntField8(1234);
        result.setIntField9(1234);
        result.setIntField10(1234);
        
        result.setStringField1("Test");
        result.setStringField2("Test");
        result.setStringField3("Test");
        result.setStringField4("Test");
        result.setStringField5("Test");
        result.setStringField6("Test");
        result.setStringField7("Test");
        result.setStringField8("Test");
        result.setStringField9("Test");
        result.setStringField10("Test");
        
        return result;
    }
    
    private static final ProviderResult100 RESULT_100 = createProviderResult100();
    
    private static ProviderResult100 createProviderResult100() {
        ProviderResult100 result = new ProviderResult100();
        
        result.setIntField1(1234);
        result.setIntField2(1234);
        result.setIntField3(1234);
        result.setIntField4(1234);
        result.setIntField5(1234);
        result.setIntField6(1234);
        result.setIntField7(1234);
        result.setIntField8(1234);
        result.setIntField9(1234);
        result.setIntField10(1234);
        result.setIntField11(1234);
        result.setIntField12(1234);
        result.setIntField13(1234);
        result.setIntField14(1234);
        result.setIntField15(1234);
        result.setIntField16(1234);
        result.setIntField17(1234);
        result.setIntField18(1234);
        result.setIntField19(1234);
        result.setIntField20(1234);
        result.setIntField21(1234);
        result.setIntField22(1234);
        result.setIntField23(1234);
        result.setIntField24(1234);
        result.setIntField25(1234);
        result.setIntField26(1234);
        result.setIntField27(1234);
        result.setIntField28(1234);
        result.setIntField29(1234);
        result.setIntField30(1234);
        result.setIntField31(1234);
        result.setIntField32(1234);
        result.setIntField33(1234);
        result.setIntField34(1234);
        result.setIntField35(1234);
        result.setIntField36(1234);
        result.setIntField37(1234);
        result.setIntField38(1234);
        result.setIntField39(1234);
        result.setIntField40(1234);
        result.setIntField41(1234);
        result.setIntField42(1234);
        result.setIntField43(1234);
        result.setIntField44(1234);
        result.setIntField45(1234);
        result.setIntField46(1234);
        result.setIntField47(1234);
        result.setIntField48(1234);
        result.setIntField49(1234);
        result.setIntField50(1234);
        result.setIntField51(1234);
        result.setIntField52(1234);
        result.setIntField53(1234);
        result.setIntField54(1234);
        result.setIntField55(1234);
        result.setIntField56(1234);
        result.setIntField57(1234);
        result.setIntField58(1234);
        result.setIntField59(1234);
        result.setIntField60(1234);
        result.setIntField61(1234);
        result.setIntField62(1234);
        result.setIntField63(1234);
        result.setIntField64(1234);
        result.setIntField65(1234);
        result.setIntField66(1234);
        result.setIntField67(1234);
        result.setIntField68(1234);
        result.setIntField69(1234);
        result.setIntField70(1234);
        result.setIntField71(1234);
        result.setIntField72(1234);
        result.setIntField73(1234);
        result.setIntField74(1234);
        result.setIntField75(1234);
        result.setIntField76(1234);
        result.setIntField77(1234);
        result.setIntField78(1234);
        result.setIntField79(1234);
        result.setIntField80(1234);
        result.setIntField81(1234);
        result.setIntField82(1234);
        result.setIntField83(1234);
        result.setIntField84(1234);
        result.setIntField85(1234);
        result.setIntField86(1234);
        result.setIntField87(1234);
        result.setIntField88(1234);
        result.setIntField89(1234);
        result.setIntField90(1234);
        result.setIntField91(1234);
        result.setIntField92(1234);
        result.setIntField93(1234);
        result.setIntField94(1234);
        result.setIntField95(1234);
        result.setIntField96(1234);
        result.setIntField97(1234);
        result.setIntField98(1234);
        result.setIntField99(1234);
        result.setIntField100(1234);
                
        result.setStringField1("Test");
        result.setStringField2("Test");
        result.setStringField3("Test");
        result.setStringField4("Test");
        result.setStringField5("Test");
        result.setStringField6("Test");
        result.setStringField7("Test");
        result.setStringField8("Test");
        result.setStringField9("Test");
        result.setStringField10("Test");
        result.setStringField11("Test");
        result.setStringField12("Test");
        result.setStringField13("Test");
        result.setStringField14("Test");
        result.setStringField15("Test");
        result.setStringField16("Test");
        result.setStringField17("Test");
        result.setStringField18("Test");
        result.setStringField19("Test");
        result.setStringField20("Test");
        result.setStringField21("Test");
        result.setStringField22("Test");
        result.setStringField23("Test");
        result.setStringField24("Test");
        result.setStringField25("Test");
        result.setStringField26("Test");
        result.setStringField27("Test");
        result.setStringField28("Test");
        result.setStringField29("Test");
        result.setStringField30("Test");
        result.setStringField31("Test");
        result.setStringField32("Test");
        result.setStringField33("Test");
        result.setStringField34("Test");
        result.setStringField35("Test");
        result.setStringField36("Test");
        result.setStringField37("Test");
        result.setStringField38("Test");
        result.setStringField39("Test");
        result.setStringField40("Test");
        result.setStringField41("Test");
        result.setStringField42("Test");
        result.setStringField43("Test");
        result.setStringField44("Test");
        result.setStringField45("Test");
        result.setStringField46("Test");
        result.setStringField47("Test");
        result.setStringField48("Test");
        result.setStringField49("Test");
        result.setStringField50("Test");
        result.setStringField51("Test");
        result.setStringField52("Test");
        result.setStringField53("Test");
        result.setStringField54("Test");
        result.setStringField55("Test");
        result.setStringField56("Test");
        result.setStringField57("Test");
        result.setStringField58("Test");
        result.setStringField59("Test");
        result.setStringField60("Test");
        result.setStringField61("Test");
        result.setStringField62("Test");
        result.setStringField63("Test");
        result.setStringField64("Test");
        result.setStringField65("Test");
        result.setStringField66("Test");
        result.setStringField67("Test");
        result.setStringField68("Test");
        result.setStringField69("Test");
        result.setStringField70("Test");
        result.setStringField71("Test");
        result.setStringField72("Test");
        result.setStringField73("Test");
        result.setStringField74("Test");
        result.setStringField75("Test");
        result.setStringField76("Test");
        result.setStringField77("Test");
        result.setStringField78("Test");
        result.setStringField79("Test");
        result.setStringField80("Test");
        result.setStringField81("Test");
        result.setStringField82("Test");
        result.setStringField83("Test");
        result.setStringField84("Test");
        result.setStringField85("Test");
        result.setStringField86("Test");
        result.setStringField87("Test");
        result.setStringField88("Test");
        result.setStringField89("Test");
        result.setStringField90("Test");
        result.setStringField91("Test");
        result.setStringField92("Test");
        result.setStringField93("Test");
        result.setStringField94("Test");
        result.setStringField95("Test");
        result.setStringField96("Test");
        result.setStringField97("Test");
        result.setStringField98("Test");
        result.setStringField99("Test");
        result.setStringField100("Test");
        
        return result;
    }
    
    public ProviderResult10 testMethod10(ProviderParameter parameter) {
        return RESULT_10;
    }
    
    public ProviderResult100 testMethod100(ProviderParameter parameter) {
        return RESULT_100;
    }

}
